- name: Create VM dirs
  hosts: all
  gather_facts: no
  tags: ["always"]
  tasks:

    - name: Create needed openjdk11 dir
      file:
        path: /home/vagrant/openjdk11
        owner: vagrant
        group: vagrant
        mode: '0755'
        state: directory

    - name: Create needed midpoint dir
      file:
        path: /home/vagrant/midpoint
        owner: vagrant
        group: vagrant
        mode: '0755'
        state: directory


- name: Setup VM
  hosts: all
  gather_facts: no
  tags: ["always"]
  become: yes

  tasks:

    - name: Download openjdk11
      get_url: 
        url: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
        dest: /home/vagrant/
        validate_certs: false
        timeout: 3600
        
    - name: Untar openjdk11
      unarchive:
        src: /home/vagrant/openjdk-11.0.2_linux-x64_bin.tar.gz
        dest: /home/vagrant/openjdk11
        group: vagrant
        owner: vagrant

    - name: Set JAVA_HOME
      lineinfile:
        dest: /etc/environment
        line: JAVA_HOME="/home/vagrant/openjdk11/jdk-11.0.2"

    - name: Download evolveum midpoint
      get_url: 
        url: https://evolveum.com/downloads/midpoint/4.7.1/midpoint-4.7.1-dist.tar.gz
        dest: /home/vagrant/
        validate_certs: false
        timeout: 3600

    - name: Untar evolveum midpoint
      unarchive:
        src: /home/vagrant/midpoint-4.7.1-dist.tar.gz
        dest: /home/vagrant/midpoint
        group: vagrant
        owner: vagrant

    - name: Start midpoint server
      command: sh /home/vagrant/midpoint/midpoint-4.7.1/bin/start.sh
